
./target/x86_64-unknown-neoos-musl/release/rust:     file format elf64-x86-64


Disassembly of section .comment:

0000000000000000 <.comment>:
   0:	4c 69 6e 6b 65 72 3a 	imul   r13,QWORD PTR [rsi+0x6b],0x203a7265
   7:	20 
   8:	4c                   	rex.WR
   9:	4c                   	rex.WR
   a:	44 20 31             	and    BYTE PTR [rcx],r14b
   d:	35 2e 30 2e 37       	xor    eax,0x372e302e
	...
